In [1]:
import pandas as pd, numpy as np
import json, os

In [2]:
DATA_PATH = "../data/"

In [3]:
os.listdir(DATA_PATH)

['links.csv', '.DS_Store', 'movies_metadata.csv', 'ratings.csv']

In [6]:
movies = pd.read_csv(DATA_PATH+"movies_metadata.csv")

/var/folders/4s/6bgg34vx40g7xpv4_54z7_bc0000gn/T/ipykernel_10007/3844791604.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv(DATA_PATH+"movies_metadata.csv")

In [4]:
def parse_dict(d, key):
    try:
        name = eval(d)[key]
        return name
    except:
        return ""

def parse_lst_dict(lst, key):
    names = []
    try:
        for d in eval(lst):
            names.append(d[key])
    except:
        pass
    return names

In [7]:
eval(movies.iloc[0]['belongs_to_collection'])

{'id': 10194,
 'name': 'Toy Story Collection',
 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg',
 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}

In [8]:
links = pd.read_csv(DATA_PATH+'links.csv')
ratings = pd.read_csv(DATA_PATH+'ratings.csv')

In [6]:
links

       movieId   imdbId    tmdbId
0            1   114709     862.0
1            2   113497    8844.0
2            3   113228   15602.0
3            4   114885   31357.0
4            5   113041   11862.0
...        ...      ...       ...
45838   176269  6209470  439050.0
45839   176271  2028550  111109.0
45840   176273   303758   67758.0
45841   176275     8536  227506.0
45842   176279  6980792  461257.0

[45843 rows x 3 columns]

In [7]:
ratings

          userId  movieId  rating   timestamp
0              1      110     1.0  1425941529
1              1      147     4.5  1425942435
2              1      858     5.0  1425941523
3              1     1221     5.0  1425941546
4              1     1246     5.0  1425941556
...          ...      ...     ...         ...
26024284  270896    58559     5.0  1257031564
26024285  270896    60069     5.0  1257032032
26024286  270896    63082     4.5  1257031764
26024287  270896    64957     4.5  1257033990
26024288  270896    71878     2.0  1257031858

[26024289 rows x 4 columns]

In [14]:
movies

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [18]:
movies['collection'] = movies['belongs_to_collection'].apply(lambda x: parse_dict(x, 'name'))

In [18]:
movies

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,collection
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,Toy Story Collection
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,Grumpy Old Men Collection
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,Father of the Bride Collection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0,
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0,
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0,
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0,
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0,

In [19]:
movies['genre'] = movies['genres'].apply(lambda x: parse_lst_dict(x, 'name'))

In [20]:
movies['languages'] = movies['spoken_languages'].apply(lambda x: parse_lst_dict(x, 'name'))

In [22]:
movies.shape

(45466, 27)

In [21]:
movies.drop(['belongs_to_collection', 'genres', 'homepage', 'imdb_id', 'original_language', 'production_companies',\
            'production_countries', 'title', 'video', 'poster_path', 'spoken_languages'], axis=1, inplace=True)

In [24]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'collection', 'genre', 'languages'],
      dtype='object')

In [22]:
movies.drop(['poster_path', 'spoken_languages'], axis=1, inplace=True)

In [23]:
movies

,adult,budget,id,original_title,overview,popularity,release_date,revenue,runtime,status,tagline,vote_average,vote_count,collection,genre,languages
0,False,30000000,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033.0,81.0,Released,NaN,7.7,5415.0,Toy Story Collection,"[Animation, Comedy, Family]",[English]
1,False,65000000,8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,262797249.0,104.0,Released,Roll the dice and unleash the excitement!,6.9,2413.0,,"[Adventure, Fantasy, Family]","[English, Français]"
2,False,0,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,1995-12-22,0.0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,Grumpy Old Men Collection,"[Romance, Comedy]",[English]
3,False,16000000,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,81452156.0,127.0,Released,Friends are the people who let you be yourself...,6.1,34.0,,"[Comedy, Drama, Romance]",[English]
4,False,0,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,1995-02-10,76578911.0,106.0,Released,Just When His World Is Back To Normal... He's ...,5.7,173.0,Father of the Bride Collection,[Comedy],[English]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,0,439050,رگ خواب,Rising and falling between a man and woman.,0.072051,NaN,0.0,90.0,Released,Rising and falling between a man and woman,4.0,1.0,,"[Drama, Family]",[فارسی]
45462,False,0,111109,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,2011-11-17,0.0,360.0,Released,NaN,9.0,3.0,,[Drama],[]
45463,False,0,67758,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,2003-08-01,0.0,90.0,Released,A deadly game of wits.,3.8,6.0,,"[Action, Drama, Thriller]",[English]
45464,False,0,227506,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,1917-10-21,0.0,87.0,Released,NaN,0.0,0.0,,[],[]
45465,False,0,461257,Queerama,50 years after decriminalisation of homosexual...,0.163015,2017-06-09,0.0,75.0,Released,NaN,0.0,0.0,,[],[English]

In [10]:
from sentence_transformers import SentenceTransformer

In [11]:
model = SentenceTransformer("all-distilroberta-v1")

Downloading:   0%|          | 0.00/737 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/9.86k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/653 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/15.7k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/329M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/333 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/798k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [14]:
MODEL_PATH = "../model/all-distilroberta-v1"

In [15]:
model.save(MODEL_PATH)

In [24]:
sample = movies[:30]

In [25]:
sample

,adult,budget,id,original_title,overview,popularity,release_date,revenue,runtime,status,tagline,vote_average,vote_count,collection,genre,languages
0,False,30000000,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033.0,81.0,Released,NaN,7.7,5415.0,Toy Story Collection,"[Animation, Comedy, Family]",[English]
1,False,65000000,8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,262797249.0,104.0,Released,Roll the dice and unleash the excitement!,6.9,2413.0,,"[Adventure, Fantasy, Family]","[English, Français]"
2,False,0,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,1995-12-22,0.0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,Grumpy Old Men Collection,"[Romance, Comedy]",[English]
3,False,16000000,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,81452156.0,127.0,Released,Friends are the people who let you be yourself...,6.1,34.0,,"[Comedy, Drama, Romance]",[English]
4,False,0,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,1995-02-10,76578911.0,106.0,Released,Just When His World Is Back To Normal... He's ...,5.7,173.0,Father of the Bride Collection,[Comedy],[English]
5,False,60000000,949,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,1995-12-15,187436818.0,170.0,Released,A Los Angeles Crime Saga,7.7,1886.0,,"[Action, Crime, Drama, Thriller]","[English, Español]"
6,False,58000000,11860,Sabrina,An ugly duckling having undergone a remarkable...,6.677277,1995-12-15,0.0,127.0,Released,You are cordially invited to the most surprisi...,6.2,141.0,,"[Comedy, Romance]","[Français, English]"
7,False,0,45325,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.561161,1995-12-22,0.0,97.0,Released,The Original Bad Boys.,5.4,45.0,,"[Action, Adventure, Drama, Family]","[English, Deutsch]"
8,False,35000000,9091,Sudden Death,International action superstar Jean Claude Van...,5.23158,1995-12-22,64350171.0,106.0,Released,Terror goes into overtime.,5.5,174.0,,"[Action, Adventure, Thriller]",[English]
9,False,58000000,710,GoldenEye,James Bond must unmask the mysterious head of ...,14.686036,1995-11-16,352194034.0,130.0,Released,No limits. No fears. No substitutes.,6.6,1194.0,James Bond Collection,"[Adventure, Action, Thriller]","[English, Pусский, Español]"
10,False,62000000,9087,The American President,"Widowed U.S. president Andrew Shepherd, one of...",6.318445,1995-11-17,107879496.0,106.0,Released,Why can't the most powerful man in the world h...,6.5,199.0,,"[Comedy, Drama, Romance]",[English]
11,False,0,12110,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,5.430331,1995-12-22,0.0,88.0,Released,NaN,5.7,210.0,,"[Comedy, Horror]","[English, Deutsch]"
12,False,0,21032,Balto,An outcast half-wolf risks his life to prevent...,12.140733,1995-12-22,11348324.0,78.0,Released,Part Dog. Part Wolf. All Hero.,7.1,423.0,Balto Collection,"[Family, Animation, Adventure]",[English]
13,False,44000000,10858,Nixon,An all-star cast powers this epic look at Amer...,5.092,1995-12-22,13681765.0,192.0,Released,"Triumphant in Victory, Bitter in Defeat. He Ch...",7.1,72.0,,"[History, Drama]",[English]
14,False,98000000,1408,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",7.284477,1995-12-22,10017322.0,119.0,Released,The Course Has Been Set. There Is No Turning B...,5.7,137.0,,"[Action, Adventure]","[English, Latin]"
15,False,52000000,524,Casino,The life of the gambling paradise – Las Vegas ...,10.137389,1995-11-22,116112375.0,178.0,Released,No one stays at the top forever.,7.8,1343.0,,"[Drama, Crime]",[English]
16,False,16500000,4584,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",10.673167,1995-12-13,135000000.0,136.0,Released,Lose your heart and come to your senses.,7.2,364.0,,"[Drama, Romance]",[English]
17,False,4000000,5,Four Rooms,It's Ted the Bellhop's first night on the job....,9.026586,1995-12-09,4300000.0,98.0,Released,Twelve outrageous guests. Four scandalous requ...,6.5,539.0,,"[Crime, Comedy]",[English]
18,False,30000000,9273,Ace Ventura: When Nature Calls,"Summoned from an ashram in Tibet, Ace finds hi...",8.205448,1995-11-10,212385533.0,90.0,Released,New animals. New adventures. Same hair.,6.1,1128.0,Ace Ventura Collection,"[Crime, Comedy, Adventure]",[English]
19,False,60000000,11517,Money Train,A vengeful New York transit cop decides to ste...,7.337906,1995-11-21,35431113.0,103.0,Released,"Get on, or GET OUT THE WAY!",5.4,224.0,,"[Action, Comedy, Crime]",[English]
20,False,30250000,8012,Get Shorty,Chili Palmer is a Miami mobster who gets sent ...,12.669608,1995-10-20,115101622.0,105.0,Released,"The mob is tough, but it’s nothing like show b...",6.4,305.0,Chili Palmer Collection,"[Comedy, Thriller, Crime]",[English]
21,False,0,1710,Copycat,An agoraphobic psychologist and a female detec...,10.701801,1995-10-27,0.0,124.0,Released,One man is copying the most notorious killers ...,6.5,199.0,,"[Drama, Thriller]","[English, Deutsch]"
22,False,50000000,9691,Assassins,Assassin Robert Rath arrives at a funeral to k...,11.065939,1995-10-06,30303072.0,132.0,Released,"In the shadows of life, In the business of dea...",6.0,394.0,,"[Action, Adventure, Crime, Thriller]","[English, Español, Nederlands]"
23,False,0,12665,Powder,Harassed by classmates who won't accept his sh...,12.133094,1995-10-27,0.0,111.0,Released,An extraordinary encounter with another human ...,6.3,143.0,,"[Drama, Fantasy, Science Fiction, Thriller]",[English]
24,False,3600000,451,Leaving Las Vegas,"Ben Sanderson, an alcoholic Hollywood screenwr...",10.332025,1995-10-27,49800000.0,112.0,Released,I Love You... The Way You Are.,7.1,365.0,,"[Drama, Romance]",[English]
25,False,0,16420,Othello,The evil Iago pretends to be friend of Othello...,1.845899,1995-12-15,0.0,123.0,Released,"Envy, greed, jealousy and love.",7.0,33.0,,[Drama],[English]
26,False,12000000,9263,Now and Then,Waxing nostalgic about the bittersweet passage...,8.681325,1995-10-20,27400000.0,100.0,Released,In every woman there is the girl she left behind.,6.6,91.0,,"[Comedy, Drama, Family]",[English]
27,False,0,17015,Persuasion,This film adaptation of Jane Austen's last nov...,2.228434,1995-09-27,0.0,104.0,Released,NaN,7.4,36.0,,"[Drama, Romance]",[English]
28,False,18000000,902,La Cité des Enfants Perdus,A scientist in a surrealist society kidnaps ch...,9.822423,1995-05-16,1738611.0,108.0,Released,Where happily ever after is just a dream.,7.6,308.0,,"[Fantasy, Science Fiction, Adventure]","[广州话 / 廣州話, Français]"
29,False,0,37557,摇啊摇，摇到外婆桥,A provincial boy related to a Shanghai crime f...,1.100915,1995-04-30,0.0,108.0,Released,In 1930's Shanghai violence was not the proble...,6.5,17.0,,"[Drama, Crime]",[普通话]

In [36]:
embeddings = model.encode(sample.overview.values.tolist(), convert_to_tensor=True)

Ignored unknown kwarg option direction

In [37]:
embeddings

tensor([[ 0.0454,  0.0175, -0.0139,  ..., -0.0496, -0.0783, -0.0410],
        [-0.0107, -0.0615,  0.0434,  ..., -0.0119, -0.0693, -0.0351],
        [ 0.0258, -0.0394, -0.0010,  ..., -0.0280,  0.0153,  0.0295],
        ...,
        [ 0.0076, -0.0396, -0.0097,  ..., -0.0659, -0.0074,  0.0645],
        [-0.0176, -0.0368,  0.0074,  ..., -0.0400,  0.0291, -0.0043],
        [-0.0130, -0.1006, -0.0540,  ..., -0.0254, -0.0159,  0.0393]])

In [28]:
from sentence_transformers import util

In [29]:
embeddings.shape

(30, 768)

In [31]:
query = [movies.iloc[60]['overview']]

In [32]:
query

["It's fire and brimstone time as grieving mother Karen McCann takes justice into her own hands when a kangaroo court in Los Angeles fails to convict Robert Doob, the monster who raped and murdered her 17-year-old daughter."]

In [38]:
query_embedding = model.encode(query, convert_to_tensor=True)

Ignored unknown kwarg option direction

In [40]:
embeddings = util.normalize_embeddings(embeddings)
query_embedding = util.normalize_embeddings(query_embedding)

In [50]:
hits = util.semantic_search(query_embedding, embeddings, score_function=util.dot_score, top_k=30)

In [51]:
hits

[[{'corpus_id': 22, 'score': 0.42187267541885376},
  {'corpus_id': 7, 'score': 0.3681718409061432},
  {'corpus_id': 11, 'score': 0.36179715394973755},
  {'corpus_id': 16, 'score': 0.34505385160446167},
  {'corpus_id': 3, 'score': 0.3390491306781769},
  {'corpus_id': 14, 'score': 0.2915712594985962},
  {'corpus_id': 27, 'score': 0.28844374418258667},
  {'corpus_id': 8, 'score': 0.2800387442111969},
  {'corpus_id': 21, 'score': 0.2733672261238098},
  {'corpus_id': 5, 'score': 0.25827619433403015},
  {'corpus_id': 23, 'score': 0.2517414391040802},
  {'corpus_id': 19, 'score': 0.2493610382080078},
  {'corpus_id': 26, 'score': 0.24535776674747467},
  {'corpus_id': 2, 'score': 0.2331644594669342},
  {'corpus_id': 9, 'score': 0.23167890310287476},
  {'corpus_id': 12, 'score': 0.2305038720369339},
  {'corpus_id': 18, 'score': 0.23009246587753296},
  {'corpus_id': 20, 'score': 0.22589069604873657},
  {'corpus_id': 1, 'score': 0.22031617164611816},
  {'corpus_id': 24, 'score': 0.21887120604515076},
  {'corpus_id': 6, 'score': 0.20174063742160797},
  {'corpus_id': 28, 'score': 0.19695058465003967},
  {'corpus_id': 29, 'score': 0.19057750701904297},
  {'corpus_id': 17, 'score': 0.18837015330791473},
  {'corpus_id': 4, 'score': 0.18691864609718323},
  {'corpus_id': 15, 'score': 0.18342940509319305},
  {'corpus_id': 13, 'score': 0.180110901594162},
  {'corpus_id': 0, 'score': 0.1366954743862152},
  {'corpus_id': 10, 'score': 0.1362389624118805},
  {'corpus_id': 25, 'score': 0.1057463213801384}]]

In [43]:
movies

,adult,budget,id,original_title,overview,popularity,release_date,revenue,runtime,status,tagline,vote_average,vote_count,collection,genre,languages
0,False,30000000,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033.0,81.0,Released,NaN,7.7,5415.0,Toy Story Collection,"[Animation, Comedy, Family]",[English]
1,False,65000000,8844,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,262797249.0,104.0,Released,Roll the dice and unleash the excitement!,6.9,2413.0,,"[Adventure, Fantasy, Family]","[English, Français]"
2,False,0,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,1995-12-22,0.0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,Grumpy Old Men Collection,"[Romance, Comedy]",[English]
3,False,16000000,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,81452156.0,127.0,Released,Friends are the people who let you be yourself...,6.1,34.0,,"[Comedy, Drama, Romance]",[English]
4,False,0,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,1995-02-10,76578911.0,106.0,Released,Just When His World Is Back To Normal... He's ...,5.7,173.0,Father of the Bride Collection,[Comedy],[English]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,0,439050,رگ خواب,Rising and falling between a man and woman.,0.072051,NaN,0.0,90.0,Released,Rising and falling between a man and woman,4.0,1.0,,"[Drama, Family]",[فارسی]
45462,False,0,111109,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,0.178241,2011-11-17,0.0,360.0,Released,NaN,9.0,3.0,,[Drama],[]
45463,False,0,67758,Betrayal,"When one of her hits goes wrong, a professiona...",0.903007,2003-08-01,0.0,90.0,Released,A deadly game of wits.,3.8,6.0,,"[Action, Drama, Thriller]",[English]
45464,False,0,227506,Satana likuyushchiy,"In a small town live two brothers, one a minis...",0.003503,1917-10-21,0.0,87.0,Released,NaN,0.0,0.0,,[],[]
45465,False,0,461257,Queerama,50 years after decriminalisation of homosexual...,0.163015,2017-06-09,0.0,75.0,Released,NaN,0.0,0.0,,[],[English]

In [52]:
movies.isna().sum()

adult                 0
budget                0
id                    0
original_title        0
overview            954
popularity            5
release_date         87
revenue               6
runtime             263
status               87
tagline           25054
vote_average          6
vote_count            6
collection            0
genre                 0
languages             0
dtype: int64

In [53]:
movies.dropna(subset='overview', inplace=True)

In [54]:
movies.isna().sum()

adult                 0
budget                0
id                    0
original_title        0
overview              0
popularity            5
release_date         74
revenue               6
runtime               6
status               71
tagline           24108
vote_average          6
vote_count            6
collection            0
genre                 0
languages             0
dtype: int64